CREATE TABLE jokes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL UNIQUE,
    author VARCHAR(255) NOT NULL,
    category VARCHAR(50) DEFAULT 'general',
    likes INTEGER DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_jokes_category ON jokes(category);